### ISSUE TITLE
How do I manually trigger the refresh?

### ISSUE THREAD

**Issue by FokkeZB** [iskugor/Ti.SwipeRefreshLayout#4]
I tried `setRefreshing(true)` but that gives:

```
[DEBUG] OpenGLRenderer: Enabling debug mode 0
[WARN]  W/System.err: java.lang.NullPointerException
[WARN]  W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefreshLayout.ensureTarget(SwipeRefreshLayout.java:312)
[WARN]  W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefreshLayout.setRefreshing(SwipeRefreshLayout.java:255)
[WARN]  W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefresh.setRefreshing(SwipeRefresh.java:88)
[WARN]  W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefreshProxy.setRefreshing(SwipeRefreshProxy.java:27)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:99)
[WARN]  W/System.err: 	at ti.modules.titanium.ui.TabGroupProxy.handleMessage(TabGroupProxy.java:104)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:137)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] TiExceptionHandler: (main) [510,510] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,510] - In alloy/widgets/nl.fokkezb.pullToRefresh/controllers/widget.js:25,24
[ERROR] TiExceptionHandler: (main) [1,511] - Message: Uncaught Error: Java Exception occurred
[ERROR] TiExceptionHandler: (main) [0,511] - Source:         refreshControl.setRefreshing(true);
[ERROR] V8Exception: Exception occurred at alloy/widgets/nl.fokkezb.pullToRefresh/controllers/widget.js:25: Uncaught Error: Java Exception occurred
```

**Comment by iskugor** [comment]
Hi. Check out 0.4.1 module version (in "dist" folder), it should fix crash.

**Comment by FokkeZB** [comment]
Thanks @iskugor 

https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/releases/tag/2.0.1
